DEF_OP(OP_MUL, *)
DEF_OP(OP_DIV, /)
DEF_OP(OP_ADD, +)
DEF_OP(OP_SUB, -)
DEF_OP(OP_SQRT, sqrt)
DEF_OP(OP_LE, <=)
DEF_OP(OP_ME, >=)
DEF_OP(OP_ASS, =)
DEF_OP(OP_NE, !=)
DEF_OP(OP_EQ, ==)
DEF_OP(OP_L, >)
DEF_OP(OP_M, <)
DEF_OP(OP_IN, in)
DEF_OP(OP_OUT, out)
DEF_OP(OP_IF, if)
DEF_OP(OP_WHILE, while)
DEF_OP(OP_TZ, ;)
DEF_OP(OP_RET, return)
DEF_OP(OP_FUNC, function)


